### ISSUE TITLE
获取数据后如何解析

### ISSUE THREAD

**Issue by 2966325911** [HuRuWo/SerialPortHelper#1]
当从串口获取数据后，如何完整的解析一个命令，比如判断头，尾，校验码，判断一个数据是否完整接收等问题，能否大体举例说明一下

**Comment by HuRuWo** [comment]
这个解析和软件没有关系了吧 ，你只要保证能拿到数据

所谓的头尾校验码 这是协议相关的东西 需要结合协议

而数据位对应的功能状态 都是应该写在设备的开发文档中
